version: "3"

services:
  pg:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - net

  elixir_app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - DATABASE_URL=${DATABASE_URL}
      - PHX_HOST=${PHX_HOST}
      - PHX_SERVER=${PHX_SERVER}
    ports:
      - "4000:4000"
    depends_on:
      - pg
    networks:
      - net

volumes:
  pgdata:

networks:
  net:
    driver: bridge
